### ISSUE TITLE
Properties with default values in AS3 schema should not be added in the converted AS3 declaration by ACC

### ISSUE THREAD

**Issue by rjouhann** [f5devcentral/f5-as3-config-converter#11]
### Environment
 * Application Services Version: 3.24
 * BIG-IP Version: 16.0

### Summary
translateServerAddress, translateServerPort, layer4 and snat being by default set to true in the AS3 schema, so they should not be added into the generated AS3 declaration by ACC.

### Steps To Reproduce
1. Convert following config:
```conf
ltm virtual /Common/BCA_VS_FTP {
    creation-time 2021-02-01:19:22:20
    destination /Common/10.8.239.182:21
    ip-protocol tcp
    last-modified-time 2021-02-01:19:25:14
    mask 255.255.255.255
    pool /Common/BCA_Pool_FTP
    profiles {
        /Common/Epic_TCP {
            context clientside
        }
        /Common/f5-tcp-wan {
            context serverside
        }
    }
    rules {
        /Common/BCA_FTP_Whitelist
    }
    serverssl-use-sni disabled
    source 0.0.0.0/0
    source-address-translation {
        type automap
    }
    translate-address enabled
    translate-port enabled
}
```

2. Generated the following AS3 declaration
```out
            "BCA_VS_FTP": {
                "layer4": "tcp",
                "pool": "BCA_Pool_FTP",
                "iRules": [
                    {
                        "use": "/Common/Shared/BCA_FTP_Whitelist"
                    }
                ],
                "translateServerAddress": true,
                "translateServerPort": true,
                "class": "Service_TCP",
                "profileTCP": {
                    "ingress": {
                        "use": "/Common/Shared/Epic_TCP"
                    }
                },
                "virtualAddresses": [
                    "10.8.239.182"
                ],
                "virtualPort": 21,
                "persistenceMethods": [],
                "snat": "auto"
            },
```

### Expected Behavior
**"translateServerAddress": true,**, **"translateServerPort": true,**, **"layer4": "tcp",** and **"snat": "auto"** should not be included in the output

see AS3 schema reference https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#service-tcp.

- translateServerAddress (boolean) | true | true, false | If true (default), make server-side connection to server address (otherwise, treat server as gateway to virtual-server address)
- translateServerPort (boolean) | true | true, false | If true (default), make server-side connection to server port (otherwise, connect to server on virtual-server port)
- layer4 (string) | “tcp” | “tcp” | For TCP virtual server, Layer 4 protocol must be TCP
- snat (string \| Service_TCP_snat) | “auto” | “none”, “self”, “auto”, - | Name of built-in SNAT method or AS3 pointer to SNAT pool. If ‘self’, the system uses the virtual-server address as SNAT address

### Actual Behavior
**"translateServerAddress": true,**, **"translateServerPort": true,**, **"layer4": "tcp",** and **"snat": "auto"** are included in the generated AS3 declaration by ACC.

**Comment by mdditt2000** [comment]
Jira is done in ACC 1.11. Closing issue
