### ISSUE TITLE
[RFE] create DO output

### ISSUE THREAD

**Issue by DumpySquare** [f5devcentral/f5-as3-config-converter#16]
### Is your feature request related to a problem? Please describe.
Not a problem, but it would be super handy and drive DO adoption if we had a similar function to take a TMOS config and return all the settings DO would handle.  This could be a quick and easy way to templatize an F5's base/system settings and deploy more  devices with the same system settings.

### Describe the solution you'd like
This may be best in another project (like ACC), or I could do something in vscode-f5/f5-corkscrew/f5-conx-core, but just wanted to get the idea out there.

Since this project is already doing TMOS->AS3 conversion, and now utilizing a REST API integration, a different API endpoint, or parameter could tell the engine to return a DO conversion instead of an AS3, could be an easy addition.  

Examples below:

New API endpoint:
- http://localhost:8080/apiV1/doConvert

As existing endpoint param:
- http://localhost:8080/as3convert?do=true

### Describe alternatives you've considered
Currently, there is no alternative.  DO declarations must be made by hand at some point

### Additional context
A small tool like this could be incredibly valuable for helping users transition to automation tools like DO.  With the output from a tool like this, it would easily be converted to a FAST template and templatize/standardize deployments even more.   Like ACC, this would drastically reduce the time/expertise needed to get started with DO.  This could also be incorporated into workflows that assist users with migrating to next gen cloud based platforms.

**Comment by mdditt2000** [comment]
Spike CHARON-269 created for PM tracking. Spike in progress

**Comment by mdditt2000** [comment]
Added to ACC 1.14 as a preview. Will update this issue with supported classes and docs

**Comment by mdditt2000** [comment]
docker run --rm -v  "$PWD":/app/data f5-as3-config-converter:1.15.0-RC2 -o data/v14-output.json -u data/v14-test.ucs --declarative-onboarding

Can be closed. More classes supported in ACC 1.15, 1.16 etc.
