### ISSUE TITLE
Unsupported ltm node

### ISSUE THREAD

**Issue by makagonr** [f5devcentral/f5-as3-config-converter#20]
### Environment
 * AS3 converter: 1.11.0-RC1 used as service with "serve" flag

### Summary
When passing ltm node to ACC converter, I got this as unsupported-  I figured it out by altering the code and forcing printing unsupported obejcts to output, because of the first issue

### Steps To Reproduce
[bigip.conf.zip](https://github.com/f5devcentral/f5-as3-config-converter/files/6204685/bigip.conf.zip)
Convert attached bigip.conf to observe the issue

docker run --rm -v "$PWD":/app/data f5-as3-config-converter:1.11.0-RC1  -o test.json -c /data/bigip.conf --unsupported

### Expected Behavior
"ltm node" should not be classified as unsupported

**Comment by mdditt2000** [comment]
This was resolved in ACC 1.12
