### ISSUE TITLE
Node error in output

### ISSUE THREAD

**Issue by kjdms** [f5devcentral/f5-as3-config-converter#23]
### Environment
 * Application Services Version: 1.11.0
 * BIG-IP Version: 14.1.2.8
 * Red Hat 8.3

### Summary
Error when running against my UCS file. Reproducible on demand. The tool will complete if I limit it to one virtual server. Created F5 support case C3561341 to upload the UCS file in question.

### Steps To Reproduce
1. Run the following command:
```
$ sudo podman run --pull=never --rm -v  "$PWD":/app/data f5-as3-config-converter:v1.11.0 -o data/shdc-viprion02.json -u data/MyUCS-2021_04_27-06_00.ucs
```

2. Observe the following error message:
```(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at findSchemaDefault (/app/src/removeDefaultValues.js:40:30)
    at /app/src/removeDefaultValues.js:62:33
    at Array.forEach (<anonymous>)
    at matchDefaults (/app/src/removeDefaultValues.js:60:10)
    at /app/src/removeDefaultValues.js:80:20
    at Array.forEach (<anonymous>)
    at findProfiles (/app/src/removeDefaultValues.js:76:10)
    at /app/src/removeDefaultValues.js:78:24
    at Array.forEach (<anonymous>)
    at findProfiles (/app/src/removeDefaultValues.js:76:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Expected Behavior
No node errors in output.

### Actual Behavior
Command fails with no output to file. STDERR is listed above.

**Comment by mdditt2000** [comment]
@kjdms morning. Please can you send me a email message at m.dittmer@f5.com so i can get your UCS file to reproduce this and possibly open a bug. It could be viprion related.

**Comment by mdditt2000** [comment]
@kjdms got the UCS file. Thank you. Going to look at it this afternoon. Standby!

**Comment by mdditt2000** [comment]
please note ACC is community supported i have taken ownership of SR C3561341

**Comment by mdditt2000** [comment]
Created Jira request CHARON-254 for PM tracking. Requesting PD look to see why ACC cannot open this UCS file. I am going to try corkscrew aka F5 vscode extension to see if that will open this UCS file.

**Comment by mdditt2000** [comment]
@kjdms bug is in code-review. Will provide image once available. Thanks

**Comment by mdditt2000** [comment]
Closing this issue. Provided RC to @kjdms
