### ISSUE TITLE
Invalid SSL certificate reference in profile

### ISSUE THREAD

**Issue by makagonr** [f5devcentral/f5-as3-config-converter#24]
### Summary
I am trying to use ACC to convert bigip.conf with ssl profile into AS3, but the output I receive contains wrong reference to the certificate - the certificate is created inside the application, and refers to cert and key files that are inside bigip /Common partition, but the profile contains broken AS3 reference.

### Steps To Reproduce
1. Convert attached bigip.conf.txt file into AS3 using "f5devcentral/f5-as3-config-converter:1.11.0" image

2. Observe that generated
"testing_cert" object is placed inside the application, but 
"test-iapp-1_client-ssl" profile refers to "/Common/Shared/testing_cert"

### Expected Behavior
"test-iapp-1_client-ssl" should refer to "testing_cert" or "/testing_tenant/test_app/testing_cert"

Regards
[bigip.conf.txt](https://github.com/f5devcentral/f5-as3-config-converter/files/6466502/bigip.conf.txt)

[output.json.txt](https://github.com/f5devcentral/f5-as3-config-converter/files/6466508/output.json.txt)

**Comment by mdditt2000** [comment]
@makagonr i agree with the expected behavior. Thanks for reporting! I will pas on to PD.

**Comment by mdditt2000** [comment]
Filed Jira CHARON-261 for PM tracking. Requesting resolution for ACC 1.12

**Comment by makagonr** [comment]
Thanks!

śr., 12 maj 2021 o 17:19 mark dittmer ***@***.***> napisał(a):

**Comment by mdditt2000** [comment]
issue is resolved and in 1.12. Closing issue out. @makagonr i will send you the latest RC for 1.12
