### ISSUE TITLE
policyEndpoint references missing Application class name

### ISSUE THREAD

**Issue by frslater** [f5devcentral/f5-as3-config-converter#30]
### Environment
 * Application Services Version: 1.11.0

### Summary
When virtuals have ltm policies attached, the resulting AS3 config is an Endpoint_Policy class object in /Common/Shared and a "policyEndpoint" property in the Service class object.  ACC is specifying policyEndpoint without "Shared" (the Application class name).  i.e. "policyEndpoint": "/Common/xxx" should be   "policyEndpoint": "/Common/Shared/xxx"

**Comment by v-zhuravlev-f5** [comment]
Charon-302 Jira issue created to track it.

**Comment by mdditt2000** [comment]
Merge branch 'policyEndpoint' into 'develop' - Closing issue. Will be released in ACC 1.13
