### ISSUE TITLE
Conversion does not seem to finish

### ISSUE THREAD

**Issue by afreudenreich** [f5devcentral/f5-as3-config-converter#45]
### Environment
 * Application Services Version: f5-as3-config-converter:v1.13.0
 * BIG-IP Version: 14.1.4

### Summary
When running the conversion against a ucs file it does not seem to finish - no visible output (I let it run for more than 6 hours before killing it).

### Steps To Reproduce
docker run --rm -v  "$PWD":/app/data f5-as3-config-converter:v1.13.0 -o data/as3_conversion_test.json -u data/test.ucs

Observed the following:
No output at all - process just keeps running
docker.cli process does not seem to use any CPU.

### Expected Behavior
Finishes after less than an hour (?).

### Actual Behavior
Does not finish.

**Comment by mdditt2000** [comment]
@afreudenreich i am able to open your UCS file with the vscode f5 extension and browse the application. If i convert each application you should have a issue. Do you have some time to setup a meeting. Please can we schedule something with @buulam

**Comment by afreudenreich** [comment]
@mdditt2000 thanks Mark - I did not know about the F5 extension for VSCode - that looks promising!
I still have asked Buu to setup a meeting.

**Comment by mdditt2000** [comment]
Issue recreated

```
Desktop$ docker run --rm -v  "$PWD":/app/data f5-as3-config-converter:1.15.0-RC1 -o data/bigip.json -u data/github45.ucs

Nothing!!!!!

Desktop$ 

```

**Comment by mdditt2000** [comment]
Created Jira CHARON-423 for PM tracking

**Comment by mdditt2000** [comment]
Unpacked config has issues only in bigip.conf. All other .conf files looks good

**Comment by mdditt2000** [comment]
Issue solved - Merge branch
