### ISSUE TITLE
Error extracting specified UCS, please check the filepath

### ISSUE THREAD

**Issue by difanzhao** [f5devcentral/f5-as3-config-converter#50]
### Environment
 * Application Services Version: tried both v1.13.0 and v1.14.0
 * BIG-IP Version: 14.1.4.3

### Summary
I am trying to convert my UCS file for the first time on my Redhat 7.8 box but I constantly getting this extracting error.
The UCS file should be ok. I sent the file to my F5 account rep and he is able to convert it.

### Steps To Reproduce
Run the command:
```sudo docker run --rm -v "$PWD":/app/data f5-as3-config-converter:v1.14.0 -o data/test.json -u data/uw2-arm-cld-01-ltm-qut-a0_before_AS3.ucs```

I also tried different paths. Is the path here for the UCS file "data/xxx" the path for my OS, or the path inside the docker image?
Please help. Thanks!

```sudo docker run --rm -v "$PWD":/app/data f5-as3-config-converter:v1.14.0 -o /home/difzhao/test.json -u /home/difzhao/uw2-arm-cld-01-ltm-qut-a0_before_AS3.ucs```

### Expected Behavior
I expect a converted JSON file to be generated

### Actual Behavior
```$ sudo docker run --rm -v "$PWD":/app/data f5-as3-config-converter:v1.14.0 -o data/test.json -u /home/difzhao/uw2-arm-cld-01-ltm-qut-a0_before_AS3.ucs
2021-09-01 23:02:47 ERROR Error extracting specified UCS, please check the filepath.
```

**Comment by mdditt2000** [comment]
@difanzhao please can i get access to the UCS file.

**Comment by mdditt2000** [comment]
Will check today on a RedHat machine!

**Comment by mdditt2000** [comment]
@difanzhao you seeing the following issue below?

```
[root@localhost 50]# docker run --rm -v "$PWD":/app/data docker.io/mdditt2000/f5-as3-config-converter:1.15.0-RC3 -o data/test.json -u data/v14-test.ucs
2021-09-09 22:32:04 ERROR Error extracting specified UCS, please check the filepath.

```

**Comment by difanzhao** [comment]
Hi

**Comment by difanzhao** [comment]
Sorry I fat finger'ed and "closed" the case by mistake... yes Mdditt2000, this is exactly the error I see... Do you still need the ucs file or you are able to reproduce the issue? The ucs file should be good because my F5 account rep is able to convert it with the same acc version running on his ubuntu WSL.

**Comment by mdditt2000** [comment]
no worries. I have made the same mistake many times. No need for the UCS file as i can recreate the issue. I will file a internal JIRA with product development. ACC cannot seem to locate the source folder.

**Comment by mdditt2000** [comment]
Created CHARON-449 for internal tracking.

**Comment by mdditt2000** [comment]
Setting milestone but cannot commit until meeting with dev

**Comment by difanzhao** [comment]
Thanks Mark!

**Comment by mdditt2000** [comment]
Resolved
