### ISSUE TITLE
Expose "stdout/stderr" output via API

### ISSUE THREAD

**Issue by makagonr** [f5devcentral/f5-as3-config-converter#61]
### Is your feature request related to a problem? Please describe.
ACC produces output via conversion:
e.x.
```
2021-10-07 09:19:20 INFO 107 BIG-IP objects detected total
2021-10-07 09:19:20 INFO 59 BIG-IP objects recognized by AS3
2021-10-07 09:19:20 INFO 25 BIG-IP objects supported by ACC
2021-10-07 09:19:20 INFO 25 AS3 stanzas generated
```
Also sometimes there is a problem with the conversion. In such case, via CLI one can get an error.

It would be good to get such information also via API call

### Describe the solution you'd like
in a response
{
  "output": ...
  "stdout": "2021-10-07 09:19:20 INFO 107 BIG-IP objects detected total\n2021-10-07 09:19:20 INFO 59 BIG-IP objects recognized by AS3...",
   "stderr": "..."
}

**Comment by mdditt2000** [comment]
Closing out. Provided information to team via JIRA

**Comment by azahajkiewicz** [comment]
@mdditt2000 Hi Mark, this Jira item doesn't look like a fix for the issue. Can you confirm it with the team?

**Comment by sschadwick** [comment]
Jira issue created as CHARON-542.

**Comment by p-semenov-f5** [comment]
Hello!

Chariot is consuming stdout and stderr directly. Do you know about that? Can you use chariot api?

**Comment by makagonr** [comment]
Hello,

We use the API, and we would like to get the content of stdout/stderr
generated by processing the request in order to show it to the user when
some objects are not compatible or we get 4xx/5xx http codes for some
reason.

Regards
Rafał Makagon

pt., 3 gru 2021 o 18:36 p-semenov-f5 ***@***.***> napisał(a):

**Comment by p-semenov-f5** [comment]
Should be in ACC 1.17
